{
  "formatVersion": "1.1",
  "component": {
    "url": "../../nativeBridge-annotation/1.0.27/nativeBridge-annotation-1.0.27.module",
    "group": "com.subscribe.nativebridge.annotation",
    "module": "nativeBridge-annotation",
    "version": "1.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-annotation.klib",
          "url": "nativeBridge-annotation-iosx64-1.0.27.klib",
          "size": 23699,
          "sha512": "3fc6322e37ccb61e9279d761f93645db3f0059c98aeed1fd7e1240002b3fcd1059b2b7649d16374f6440251c4b469e8c8c88083af07f4b072f80ac81a4e6b133",
          "sha256": "367c1f4f943e58ffc0f78d27cb40d20fea78cd9dbea317270aa1819691afd9f7",
          "sha1": "622f61a4282ce530d11f7a2aae181fa3dc1ba360",
          "md5": "2e48e0f3d6ccf5c18243155e1a6aa2c1"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "nativeBridge-annotation-iosx64-1.0.27-sources.jar",
          "url": "nativeBridge-annotation-iosx64-1.0.27-sources.jar",
          "size": 8451,
          "sha512": "f01cf4aa0e95695a83c14111916b30effdb2472e6d1ccd5cb6aa2f138f31627524f34c0e58580d7e7a503daaf70de5c43f664962ee157c5222df2933d1f83eae",
          "sha256": "b2d9b2fb7a5d5ab78d66236f6628844a9ec5fa9984217e85ef54cb1e3f022127",
          "sha1": "3568d2359547b222a58d828d5d3f84b8be093fd6",
          "md5": "2cfa6890251d47563602f6cdea893f6e"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-annotation-iosx64-1.0.27-metadata.jar",
          "url": "nativeBridge-annotation-iosx64-1.0.27-metadata.jar",
          "size": 261,
          "sha512": "4c66a076db100a87ca31ebd345760ec699546102f79b2c20687ca79a5fecbd93620f62c2dbf79fbcb5bc8600459072e7db01c90cdcb1aff95204d61fa1c8cb64",
          "sha256": "004bf369cd4954656ba395b036372a6acb5903957d65c0c41b6fa8ba18a0c40f",
          "sha1": "6218b1c34df78534487fa9208f09f08b788271cf",
          "md5": "15970c167314086dab46f04578246c93"
        }
      ]
    }
  ]
}
