{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "nativeBridge-script",
    "version": "1.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "nativeBridge-script-1.0.22.jar",
          "url": "nativeBridge-script-1.0.22.jar",
          "size": 10509,
          "sha512": "a97ac633c33aca478401f8154136e139a71823cd6d1547e19bdec338aa3c277052137d8e9e2bdc0adf6434bfaf234f65c08e1a5830c8574dd6d2170f14f93adb",
          "sha256": "cd94977ee3449eb8e22c9c07f848cc4ee4ea8da98c986454c379b499a9d7b1e9",
          "sha1": "4990af7d653f65f48908d54b118dda2352f774ab",
          "md5": "628560e3774d832cf9300a1a6def3996"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.22.jar",
          "url": "nativeBridge-script-1.0.22.jar",
          "size": 10509,
          "sha512": "a97ac633c33aca478401f8154136e139a71823cd6d1547e19bdec338aa3c277052137d8e9e2bdc0adf6434bfaf234f65c08e1a5830c8574dd6d2170f14f93adb",
          "sha256": "cd94977ee3449eb8e22c9c07f848cc4ee4ea8da98c986454c379b499a9d7b1e9",
          "sha1": "4990af7d653f65f48908d54b118dda2352f774ab",
          "md5": "628560e3774d832cf9300a1a6def3996"
        }
      ]
    }
  ]
}
