{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "nativeBridge-script",
    "version": "1.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "nativeBridge-script-1.0.22.jar",
          "url": "nativeBridge-script-1.0.22.jar",
          "size": 10509,
          "sha512": "ff4fbff01d192e1ad68f3033ee78f551039ede01fba56f69c8166c0bacab475172c5c58a63b893f30b426cf1332a6ea859abfbc22dbd48dc35dfa8fd13878ac5",
          "sha256": "fe3370deb78d147cf9b43be0f234513fa7f2b3786410325cef50c96a4f232461",
          "sha1": "21b950d22d205168c16edb71f278a80302ada9c7",
          "md5": "c1b5451febf1fd1a15469c355874309f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.22.jar",
          "url": "nativeBridge-script-1.0.22.jar",
          "size": 10509,
          "sha512": "ff4fbff01d192e1ad68f3033ee78f551039ede01fba56f69c8166c0bacab475172c5c58a63b893f30b426cf1332a6ea859abfbc22dbd48dc35dfa8fd13878ac5",
          "sha256": "fe3370deb78d147cf9b43be0f234513fa7f2b3786410325cef50c96a4f232461",
          "sha1": "21b950d22d205168c16edb71f278a80302ada9c7",
          "md5": "c1b5451febf1fd1a15469c355874309f"
        }
      ]
    }
  ]
}
