{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "gradlex",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradlex-1.0.2.jar",
          "url": "gradlex-1.0.2.jar",
          "size": 17421,
          "sha512": "0873000c2498c80990e864e0b7a0f97977dac8ef014a90449262d8005dcb752dff5bb7dfd0f2521cb848831482e772504855f3f313826cf50de4e417eea8b4ff",
          "sha256": "d9bc82d5acea0841749278f445e03014a5d7d48f431b22bebed6d2bcf8c9e09c",
          "sha1": "809e416ab410ee79923c0b2b6b337403a5f48cd8",
          "md5": "e05ae2d45d4bb6d9decc049d6baa8c16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradlex-1.0.2.jar",
          "url": "gradlex-1.0.2.jar",
          "size": 17421,
          "sha512": "0873000c2498c80990e864e0b7a0f97977dac8ef014a90449262d8005dcb752dff5bb7dfd0f2521cb848831482e772504855f3f313826cf50de4e417eea8b4ff",
          "sha256": "d9bc82d5acea0841749278f445e03014a5d7d48f431b22bebed6d2bcf8c9e09c",
          "sha1": "809e416ab410ee79923c0b2b6b337403a5f48cd8",
          "md5": "e05ae2d45d4bb6d9decc049d6baa8c16"
        }
      ]
    }
  ]
}
