{
  "formatVersion": "1.1",
  "component": {
    "url": "../../nativeBridge-annotation/1.0.26/nativeBridge-annotation-1.0.26.module",
    "group": "com.subscribe.nativebridge.annotation",
    "module": "nativeBridge-annotation",
    "version": "1.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-annotation.klib",
          "url": "nativeBridge-annotation-iosx64-1.0.26.klib",
          "size": 23699,
          "sha512": "3fc6322e37ccb61e9279d761f93645db3f0059c98aeed1fd7e1240002b3fcd1059b2b7649d16374f6440251c4b469e8c8c88083af07f4b072f80ac81a4e6b133",
          "sha256": "367c1f4f943e58ffc0f78d27cb40d20fea78cd9dbea317270aa1819691afd9f7",
          "sha1": "622f61a4282ce530d11f7a2aae181fa3dc1ba360",
          "md5": "2e48e0f3d6ccf5c18243155e1a6aa2c1"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "nativeBridge-annotation-iosx64-1.0.26-sources.jar",
          "url": "nativeBridge-annotation-iosx64-1.0.26-sources.jar",
          "size": 8451,
          "sha512": "f01cf4aa0e95695a83c14111916b30effdb2472e6d1ccd5cb6aa2f138f31627524f34c0e58580d7e7a503daaf70de5c43f664962ee157c5222df2933d1f83eae",
          "sha256": "b2d9b2fb7a5d5ab78d66236f6628844a9ec5fa9984217e85ef54cb1e3f022127",
          "sha1": "3568d2359547b222a58d828d5d3f84b8be093fd6",
          "md5": "2cfa6890251d47563602f6cdea893f6e"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-annotation-iosx64-1.0.26-metadata.jar",
          "url": "nativeBridge-annotation-iosx64-1.0.26-metadata.jar",
          "size": 261,
          "sha512": "a4b13bc45ec3d5168e7c0e6184fccf57eb386c7b62ccb760852c693d0b95ebd1b55c5ef2f35b18a48764f2f82422ae4623230bf5d74b3f9d7ce30690b0238d72",
          "sha256": "9cfd849a79d890e9b9fbf5fc86305f1ece9f3fffbe03a6ab66ad6d5a8507fb87",
          "sha1": "2650e647fa6d09fd759a6b8cae1b6ca8b9150f5f",
          "md5": "a87f8d71c7ab541e70b32de8c8e2d2fa"
        }
      ]
    }
  ]
}
