{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.nativebridge.processor",
    "module": "nativeBridge-processor",
    "version": "1.0.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-processor-metadata-1.0.31.jar",
          "url": "nativeBridge-processor-1.0.31.jar",
          "size": 674,
          "sha512": "b2c2b29c88b1047a2abbf6397fccd0503db28f83abe7cd60a839f23c2f5ddfc1d25220871c14f3e54755b438102a7ea4614691d42d7fa4ef74461706af006d34",
          "sha256": "19895b13bd40d94c56b453fa03865203a8077398718e118b4c2dec54457fff5e",
          "sha1": "e4b74fd7153bc8c9070db85e13ba152d6dba447d",
          "md5": "3c4c37b0710238fdab7553b55842806d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "nativeBridge-processor-kotlin-1.0.31-sources.jar",
          "url": "nativeBridge-processor-1.0.31-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../nativeBridge-processor-jvm/1.0.31/nativeBridge-processor-jvm-1.0.31.module",
        "group": "com.subscribe.nativebridge.processor",
        "module": "nativeBridge-processor-jvm",
        "version": "1.0.31"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../nativeBridge-processor-jvm/1.0.31/nativeBridge-processor-jvm-1.0.31.module",
        "group": "com.subscribe.nativebridge.processor",
        "module": "nativeBridge-processor-jvm",
        "version": "1.0.31"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../nativeBridge-processor-jvm/1.0.31/nativeBridge-processor-jvm-1.0.31.module",
        "group": "com.subscribe.nativebridge.processor",
        "module": "nativeBridge-processor-jvm",
        "version": "1.0.31"
      }
    }
  ]
}
