{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.nativebridge",
    "module": "nativeBridge-script",
    "version": "1.0.29",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "nativeBridge-script-1.0.29.jar",
          "url": "nativeBridge-script-1.0.29.jar",
          "size": 11209,
          "sha512": "4d0dfad49f9f46683aff84188ccf6aedbe401f7c578e6bf22398621160c5290ca13f7997576348332b419b7793affcaccf4092c523c4a6be6fd301263b897acf",
          "sha256": "aef761fb1cb959558d6cc7c6bd0de389759da3306b54826ab8671bb061e88f24",
          "sha1": "04e9acf7c8aa553b226e04d339a0d7e2890baea2",
          "md5": "94b43fa06cf7c17cb781e7c10c954e79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.29.jar",
          "url": "nativeBridge-script-1.0.29.jar",
          "size": 11209,
          "sha512": "4d0dfad49f9f46683aff84188ccf6aedbe401f7c578e6bf22398621160c5290ca13f7997576348332b419b7793affcaccf4092c523c4a6be6fd301263b897acf",
          "sha256": "aef761fb1cb959558d6cc7c6bd0de389759da3306b54826ab8671bb061e88f24",
          "sha1": "04e9acf7c8aa553b226e04d339a0d7e2890baea2",
          "md5": "94b43fa06cf7c17cb781e7c10c954e79"
        }
      ]
    }
  ]
}
