{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.nativebridge",
    "module": "nativeBridge-script",
    "version": "1.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "nativeBridge-script-1.0.27.jar",
          "url": "nativeBridge-script-1.0.27.jar",
          "size": 10579,
          "sha512": "135106f294b42903293b507d8e44c5772223148197ce30bbd184bef9f2d8b8325fd7584672b8d64a135e3715e2ce6314b1cd6020a1cf7f7a632f7687ef54a39a",
          "sha256": "2e2cb265353a778c110756499062481e9e010ae4e3eb9bb004330137c027f597",
          "sha1": "4dce4c1a9254cd478f508ff6864c564a609f6e7a",
          "md5": "235088c7ac9a21e4f536df8f69a72ba7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.27.jar",
          "url": "nativeBridge-script-1.0.27.jar",
          "size": 10579,
          "sha512": "135106f294b42903293b507d8e44c5772223148197ce30bbd184bef9f2d8b8325fd7584672b8d64a135e3715e2ce6314b1cd6020a1cf7f7a632f7687ef54a39a",
          "sha256": "2e2cb265353a778c110756499062481e9e010ae4e3eb9bb004330137c027f597",
          "sha1": "4dce4c1a9254cd478f508ff6864c564a609f6e7a",
          "md5": "235088c7ac9a21e4f536df8f69a72ba7"
        }
      ]
    }
  ]
}
