{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.nativebridge",
    "module": "nativeBridge-script",
    "version": "1.0.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "nativeBridge-script-1.0.27.jar",
          "url": "nativeBridge-script-1.0.27.jar",
          "size": 10576,
          "sha512": "69d51eab10d26faf6533ef666a7635dc6e15853272f4a7c46a8be05b9c1c93465bbe1d21ed1ab671017afe2b19cc7413a814d48a0c1c1966f5c8418e9cf90e2a",
          "sha256": "5a2010cfca55318df93c16c8801556623d2225f0a0f3d4fb9ea01816e82b2ff6",
          "sha1": "519e17c1703a6f1df3bc1fab69455890810982f7",
          "md5": "c9853677d4ff7b4cd174a19797de3234"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.27.jar",
          "url": "nativeBridge-script-1.0.27.jar",
          "size": 10576,
          "sha512": "69d51eab10d26faf6533ef666a7635dc6e15853272f4a7c46a8be05b9c1c93465bbe1d21ed1ab671017afe2b19cc7413a814d48a0c1c1966f5c8418e9cf90e2a",
          "sha256": "5a2010cfca55318df93c16c8801556623d2225f0a0f3d4fb9ea01816e82b2ff6",
          "sha1": "519e17c1703a6f1df3bc1fab69455890810982f7",
          "md5": "c9853677d4ff7b4cd174a19797de3234"
        }
      ]
    }
  ]
}
