{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "nativeBridge-script",
    "version": "1.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "nativeBridge-script-1.0.23.jar",
          "url": "nativeBridge-script-1.0.23.jar",
          "size": 10509,
          "sha512": "6385d4d3cb42cc52dd9ccd6720c39fdab5aa9fcfc0056a273d902c54076e307bdde9f4cde82b0be626cea8e8647a32a760d42d33ce890180b84f3b046eed7f4d",
          "sha256": "0644ab28dbc62985532bba557275c9e901b9e9ebab3a77a7988d2b87ccf75c84",
          "sha1": "fed19d741d98075ae66f4b5c289650a719c348a7",
          "md5": "48a7a2c688f843a53ed795a6937c4873"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.23.jar",
          "url": "nativeBridge-script-1.0.23.jar",
          "size": 10509,
          "sha512": "6385d4d3cb42cc52dd9ccd6720c39fdab5aa9fcfc0056a273d902c54076e307bdde9f4cde82b0be626cea8e8647a32a760d42d33ce890180b84f3b046eed7f4d",
          "sha256": "0644ab28dbc62985532bba557275c9e901b9e9ebab3a77a7988d2b87ccf75c84",
          "sha1": "fed19d741d98075ae66f4b5c289650a719c348a7",
          "md5": "48a7a2c688f843a53ed795a6937c4873"
        }
      ]
    }
  ]
}
