{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "nativeBridge-script",
    "version": "1.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.21.jar",
          "url": "nativeBridge-script-1.0.21.jar",
          "size": 18858,
          "sha512": "8cdf1678c3fdc630c440b68fe19fdb882ee64bba0460c9c43d8bf35657f236966ce28706e0c15576073104834892d518ad89a42c73d346258fe6033b3e1cafed",
          "sha256": "1cd38833f214667966f8a103f66a239d59e30686fb0a073c713b6ce677a0b5dc",
          "sha1": "a4e0c5eb9f7b10d333429794f5f7063cc6c05502",
          "md5": "1cf894de547cdcdd5fc50f3f61835b17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.21.jar",
          "url": "nativeBridge-script-1.0.21.jar",
          "size": 18858,
          "sha512": "8cdf1678c3fdc630c440b68fe19fdb882ee64bba0460c9c43d8bf35657f236966ce28706e0c15576073104834892d518ad89a42c73d346258fe6033b3e1cafed",
          "sha256": "1cd38833f214667966f8a103f66a239d59e30686fb0a073c713b6ce677a0b5dc",
          "sha1": "a4e0c5eb9f7b10d333429794f5f7063cc6c05502",
          "md5": "1cf894de547cdcdd5fc50f3f61835b17"
        }
      ]
    }
  ]
}
