{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "nativeBridge-script",
    "version": "1.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.21.jar",
          "url": "nativeBridge-script-1.0.21.jar",
          "size": 18858,
          "sha512": "a2fadabd500868a58b8aaf6a33c56a9c5ab11f18f6a0e553d1e003b9b315775ccb68be15c574dd6418e8fec85e0c618b66db55361fa9c3772c57e650cc52bd37",
          "sha256": "7afde38bcb99a4ef12430fceaed93962ee39513a46c125beff730055d26d540f",
          "sha1": "362900fad8d44befc80416de97267350cca497d8",
          "md5": "c4ab101c9fffc4b883bd50b51f135cfc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.21.jar",
          "url": "nativeBridge-script-1.0.21.jar",
          "size": 18858,
          "sha512": "a2fadabd500868a58b8aaf6a33c56a9c5ab11f18f6a0e553d1e003b9b315775ccb68be15c574dd6418e8fec85e0c618b66db55361fa9c3772c57e650cc52bd37",
          "sha256": "7afde38bcb99a4ef12430fceaed93962ee39513a46c125beff730055d26d540f",
          "sha1": "362900fad8d44befc80416de97267350cca497d8",
          "md5": "c4ab101c9fffc4b883bd50b51f135cfc"
        }
      ]
    }
  ]
}
