{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "nativeBridge-script",
    "version": "1.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.21.jar",
          "url": "nativeBridge-script-1.0.21.jar",
          "size": 18858,
          "sha512": "e7f5873214b66d64989d94907c0c8c5e38464f56005665146092138f21b39d73d0b4202594889ab063eeb5c61a6822cf352406a9ebcf74c8f4327097b2e0c622",
          "sha256": "c97ede84338102f61774c23852fb9645db08fa5adb39153d2c82d90033ae3e92",
          "sha1": "a73fb94aaf724cfa67f5dc595456f1c5d8150631",
          "md5": "e026f4d4e00e7c3f93ba81358cb61a36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 18,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.21.jar",
          "url": "nativeBridge-script-1.0.21.jar",
          "size": 18858,
          "sha512": "e7f5873214b66d64989d94907c0c8c5e38464f56005665146092138f21b39d73d0b4202594889ab063eeb5c61a6822cf352406a9ebcf74c8f4327097b2e0c622",
          "sha256": "c97ede84338102f61774c23852fb9645db08fa5adb39153d2c82d90033ae3e92",
          "sha1": "a73fb94aaf724cfa67f5dc595456f1c5d8150631",
          "md5": "e026f4d4e00e7c3f93ba81358cb61a36"
        }
      ]
    }
  ]
}
