{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.gradlek",
    "module": "nativeBridge-script",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.3.jar",
          "url": "nativeBridge-script-1.0.3.jar",
          "size": 17458,
          "sha512": "e18c2e2134e70e935d2fc1d455a256743b6d298a1c595778e2ab4eeb4c3417af275acc2022a80f3b66d0713f04ec94221dbdd10a2d4b8e978ca54e7bcc77e191",
          "sha256": "518e62cb876905a027b9563261bc984fb71d76ecea2cb18cfd9cbd35e2199132",
          "sha1": "06a5c9dffeca397c4de7fc5824f7d651e8c89258",
          "md5": "2d6847d06a6c4378a83735a4fe5bf02d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.3.jar",
          "url": "nativeBridge-script-1.0.3.jar",
          "size": 17458,
          "sha512": "e18c2e2134e70e935d2fc1d455a256743b6d298a1c595778e2ab4eeb4c3417af275acc2022a80f3b66d0713f04ec94221dbdd10a2d4b8e978ca54e7bcc77e191",
          "sha256": "518e62cb876905a027b9563261bc984fb71d76ecea2cb18cfd9cbd35e2199132",
          "sha1": "06a5c9dffeca397c4de7fc5824f7d651e8c89258",
          "md5": "2d6847d06a6c4378a83735a4fe5bf02d"
        }
      ]
    }
  ]
}
