{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.nativebridge",
    "module": "nativeBridge-script",
    "version": "1.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "nativeBridge-script-1.0.28.jar",
          "url": "nativeBridge-script-1.0.28.jar",
          "size": 11209,
          "sha512": "8d890b3ef0aa6e4304740791fc9c3aabb1429c8f96fd3b2b45149c9893748af8b1b73909b8270b7332dc73b06e62a76551c719d5c88551d8f4a6297adee52fd5",
          "sha256": "eb28c2e8e644c5b77f2d59b33291ea7c58ed2d188aa9f357f49ada4f072d8c3e",
          "sha1": "c4eabb186fa41513d5dbe630afba94914e89774c",
          "md5": "c9140ec53d9a9d70d6323418529004ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.28.jar",
          "url": "nativeBridge-script-1.0.28.jar",
          "size": 11209,
          "sha512": "8d890b3ef0aa6e4304740791fc9c3aabb1429c8f96fd3b2b45149c9893748af8b1b73909b8270b7332dc73b06e62a76551c719d5c88551d8f4a6297adee52fd5",
          "sha256": "eb28c2e8e644c5b77f2d59b33291ea7c58ed2d188aa9f357f49ada4f072d8c3e",
          "sha1": "c4eabb186fa41513d5dbe630afba94914e89774c",
          "md5": "c9140ec53d9a9d70d6323418529004ec"
        }
      ]
    }
  ]
}
