{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.nativebridge",
    "module": "nativeBridge-script",
    "version": "1.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "nativeBridge-script-1.0.28.jar",
          "url": "nativeBridge-script-1.0.28.jar",
          "size": 10579,
          "sha512": "f3f20ccbd936c014073a19ef06a790e2e66775ada4432d4ff342344a0aceabe82ad0198cc7003de2cb7b9747c012fdaf32ff93b5e892b74a5fac68cecb4c78ee",
          "sha256": "be77cbc6a29038cb7693cb2e703f9315c0e9f3a5f49f50bcfc43c8cd8011f9e1",
          "sha1": "760c677b81aaccffb381ec4d37e7054a8e480afc",
          "md5": "6b20b6dd920bbda5362d4de9361710c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.28.jar",
          "url": "nativeBridge-script-1.0.28.jar",
          "size": 10579,
          "sha512": "f3f20ccbd936c014073a19ef06a790e2e66775ada4432d4ff342344a0aceabe82ad0198cc7003de2cb7b9747c012fdaf32ff93b5e892b74a5fac68cecb4c78ee",
          "sha256": "be77cbc6a29038cb7693cb2e703f9315c0e9f3a5f49f50bcfc43c8cd8011f9e1",
          "sha1": "760c677b81aaccffb381ec4d37e7054a8e480afc",
          "md5": "6b20b6dd920bbda5362d4de9361710c9"
        }
      ]
    }
  ]
}
