{
  "formatVersion": "1.1",
  "component": {
    "group": "com.subscribe.nativebridge",
    "module": "nativeBridge-script",
    "version": "1.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "nativeBridge-script-1.0.28.jar",
          "url": "nativeBridge-script-1.0.28.jar",
          "size": 10579,
          "sha512": "672af6711dd90e06b69d8e3b0f0610e302cbb387f060636a717af9b433698d9d3115a9c80a8182357b79fca92ff4f9b47cbe2d25e1c6fff10778bc3de522cda6",
          "sha256": "2cf251328081ab8070cae90fe09a07334fb789717730b065ea350012f5837aa1",
          "sha1": "8a37a1a9676c4aab6d6acf8f57e43f99fcabd038",
          "md5": "43ac3654eaefc9fa6826aa09cdbc6b71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-script-1.0.28.jar",
          "url": "nativeBridge-script-1.0.28.jar",
          "size": 10579,
          "sha512": "672af6711dd90e06b69d8e3b0f0610e302cbb387f060636a717af9b433698d9d3115a9c80a8182357b79fca92ff4f9b47cbe2d25e1c6fff10778bc3de522cda6",
          "sha256": "2cf251328081ab8070cae90fe09a07334fb789717730b065ea350012f5837aa1",
          "sha1": "8a37a1a9676c4aab6d6acf8f57e43f99fcabd038",
          "md5": "43ac3654eaefc9fa6826aa09cdbc6b71"
        }
      ]
    }
  ]
}
