{
  "formatVersion": "1.1",
  "component": {
    "url": "../../nativeBridge-annotation/1.0.28/nativeBridge-annotation-1.0.28.module",
    "group": "com.subscribe.nativebridge.annotation",
    "module": "nativeBridge-annotation",
    "version": "1.0.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-annotation-jvm-1.0.28.jar",
          "url": "nativeBridge-annotation-jvm-1.0.28.jar",
          "size": 21930,
          "sha512": "a2d044d3b9e6f88be48750c25fcd0eea203038e8949ff4555fd9f8989da95247d5c7685f4f48679553c53d73792d3a11aaeaa6c68d5e012a48c68580a3ee1492",
          "sha256": "26c207ce720c535efc8c959f01feb919afe6395f36f5ccb8f7e621916c8c3b13",
          "sha1": "27ec40dc325b9ff3d3282e4a7f042f4014bfe303",
          "md5": "bdd57f8d6631b06c13c4485b8333c283"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-annotation-jvm-1.0.28.jar",
          "url": "nativeBridge-annotation-jvm-1.0.28.jar",
          "size": 21930,
          "sha512": "a2d044d3b9e6f88be48750c25fcd0eea203038e8949ff4555fd9f8989da95247d5c7685f4f48679553c53d73792d3a11aaeaa6c68d5e012a48c68580a3ee1492",
          "sha256": "26c207ce720c535efc8c959f01feb919afe6395f36f5ccb8f7e621916c8c3b13",
          "sha1": "27ec40dc325b9ff3d3282e4a7f042f4014bfe303",
          "md5": "bdd57f8d6631b06c13c4485b8333c283"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "nativeBridge-annotation-jvm-1.0.28-sources.jar",
          "url": "nativeBridge-annotation-jvm-1.0.28-sources.jar",
          "size": 8451,
          "sha512": "f01cf4aa0e95695a83c14111916b30effdb2472e6d1ccd5cb6aa2f138f31627524f34c0e58580d7e7a503daaf70de5c43f664962ee157c5222df2933d1f83eae",
          "sha256": "b2d9b2fb7a5d5ab78d66236f6628844a9ec5fa9984217e85ef54cb1e3f022127",
          "sha1": "3568d2359547b222a58d828d5d3f84b8be093fd6",
          "md5": "2cfa6890251d47563602f6cdea893f6e"
        }
      ]
    }
  ]
}
