{
  "formatVersion": "1.1",
  "component": {
    "url": "../../nativeBridge-annotation/1.0.3/nativeBridge-annotation-1.0.3.module",
    "group": "com.subscribe.nativebridge.annotation",
    "module": "nativeBridge-annotation",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-annotation-jvm-1.0.3.jar",
          "url": "nativeBridge-annotation-jvm-1.0.3.jar",
          "size": 21983,
          "sha512": "f5dd39f2cd6e8960bc4411df3b5caef7c1e175c7e257ffca22ebbe711aff85c83de820fd7443c1ba87ef004af9523cd8dbf4c27dfde92ce314a8b52d6638f87d",
          "sha256": "c00e778757d4e2d9af2601cf85279d99b5c8f8d020036bf769116dd80df7bb0e",
          "sha1": "30be454aaaa080c697c7623e2ab46a7eaffd16e6",
          "md5": "32e415663b3a402f6bdb528485dc8eb2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.21.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-protobuf",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "nativeBridge-annotation-jvm-1.0.3.jar",
          "url": "nativeBridge-annotation-jvm-1.0.3.jar",
          "size": 21983,
          "sha512": "f5dd39f2cd6e8960bc4411df3b5caef7c1e175c7e257ffca22ebbe711aff85c83de820fd7443c1ba87ef004af9523cd8dbf4c27dfde92ce314a8b52d6638f87d",
          "sha256": "c00e778757d4e2d9af2601cf85279d99b5c8f8d020036bf769116dd80df7bb0e",
          "sha1": "30be454aaaa080c697c7623e2ab46a7eaffd16e6",
          "md5": "32e415663b3a402f6bdb528485dc8eb2"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "nativeBridge-annotation-jvm-1.0.3-sources.jar",
          "url": "nativeBridge-annotation-jvm-1.0.3-sources.jar",
          "size": 8451,
          "sha512": "f01cf4aa0e95695a83c14111916b30effdb2472e6d1ccd5cb6aa2f138f31627524f34c0e58580d7e7a503daaf70de5c43f664962ee157c5222df2933d1f83eae",
          "sha256": "b2d9b2fb7a5d5ab78d66236f6628844a9ec5fa9984217e85ef54cb1e3f022127",
          "sha1": "3568d2359547b222a58d828d5d3f84b8be093fd6",
          "md5": "2cfa6890251d47563602f6cdea893f6e"
        }
      ]
    }
  ]
}
